### ISSUE TITLE
Multi-output Hourglass model with no stacking and no intermediate supervision

### ISSUE THREAD

**Issue by n33lkanth** [david8862/tf-keras-stacked-hourglass-keypoint-detection#5]
Dear @david8862,
Thank you so much for this wonderful work. It is very helpful.
I am trying to implement this model in my project but with some modifications and I need your help.
I want to use only one hourglass module (no stacking) without any intermediate supervision. I want to get 4 outputs from the different resolutions of the HG module as I want to further feed these 4 outputs to RNN modules and finally get the prediction from these 4 different outputs. In short, I want to create a multi-output (4 output) model. I am facing dimensionality issues when trying to add the heads (i.e.,  head_next_stage = Add()([head, head_m, prelayerfeatures])) inside the create_heads() function. Kindly suggest what should be done in this scenario?

I am using the following arguments to create the Model:
**get_hourglass_model(11, 1, 16, mobile=False)**

The error message is displayed below:

`
Traceback (most recent call last):
  File "/Users/n33lkanth/Desktop/hourglass/model.py", line 47, in <module>
    model = get_hourglass_model(11, 1, 16, mobile=False)
  File "/Users/n33lkanth/Desktop/hourglass/model.py", line 35, in get_hourglass_model
    head_next_stage_1, head_next_stage_2, head_next_stage_4, head_next_stage_8 = hourglass_module(input_tensor, num_classes, num_channels, bottleneck, i)
  File "/Users/n33lkanth/Desktop/hourglass/blocks.py", line 21, in hourglass_module
    head_next_stage_rf2 = create_heads(bottom, rf2, num_classes, hgid, num_channels, 'rf2')
  File "/Users/n33lkanth/Desktop/hourglass/blocks.py", line 171, in create_heads
    head_next_stage = Add()([head, head_m, prelayerfeatures])
  File "/Users/n33lkanth/Environments/venv3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/Users/n33lkanth/Environments/venv3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "/Users/n33lkanth/Environments/venv3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/Users/n33lkanth/Environments/venv3.7/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "/Users/n33lkanth/Environments/venv3.7/lib/python3.7/site-packages/tensorflow/python/keras/layers/merge.py", line 112, in build
    output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
  File "/Users/n33lkanth/Environments/venv3.7/lib/python3.7/site-packages/tensorflow/python/keras/layers/merge.py", line 85, in _compute_elemwise_op_output_shape
    'together with shapes ' + str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (256, 64, 16) (512, 128, 1)
`

**Comment by david8862** [comment]
@n33lkanth  sorry for response delay. seems you're trying to create heads on different upsample layer features (rf1, rf2, rf4, rf8), but only rf1 has the same feature map size with prelayerfeatures and could do "Add" to get head.

**Comment by n33lkanth** [comment]
Dear @david8862,
Yes, you are right that I am trying to create heads on rf1, rf2, rf4, and rf8 as shown in **Figure. 1** of the [paper](https://arxiv.org/pdf/1911.06878.pdf), I am trying to take different resolution heatmaps from the Hourglass module and feed in  GRU modules. I am a bit confused if it is Ok to feed the rf1, rf2, rf4, and rf8 direct to GRU's without a head.
